### ISSUE TITLE
pipenv plugin error when using directory containing Pipfile

### ISSUE THREAD

**Issue by bodgerbarnett** [ohmyzsh/ohmyzsh#10600]
If you include the pipenv plugin in your zshrc and open a new terminal directly into a directory which contains a Pipfile, the plugin produces an error:-

> -- console output produced during zsh initialization follows --

> Launching subshell in virtual environment...
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/cli/command.py", line 393, in shell
    do_shell(
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/core.py", line 2340, in do_shell
    shell.fork_compat(*fork_args)
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/shells.py", line 121, in fork_compat
    c.interact(escape_character=None)
  File "/opt/homebrew/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 788, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (19, 'Operation not supported by device')

This issue was first mentioned in #6679 .

### Steps to reproduce

1. Create a new directory
2. cd into it
3. pipenv install requests (or anything)
4. Set your (iTerm) profile to open new windows in that directory. (I am using Visual Studio code which does this automatically, but the same thing happens)
5. Open a new terminal window.

### Expected behavior

It should not show any errors and just set the relevant pipenv environment.

### Screenshots and recordings

<img width="1152" alt="Screenshot 2022-01-19 at 12 36 36" src="https://user-images.githubusercontent.com/1990439/150132098-faf52db3-2d5e-4226-8527-0b17f2efbac7.png">

### OS / Linux distribution

macOS 12.1

### Zsh version

5.8

### Oh My Zsh version

master (957dca6)

### Terminal emulator

iTerm2, VSCode

**Comment by rahul286** [comment]
I started noticing this issue when I switched to powerlevel10k theme https://github.com/romkatv/powerlevel10k/ for my zsh setup.

I am yet to find a workaround but switching back to one of oh-my-zsh themes solved this for now.

**Comment by rahul286** [comment]
**Update**

I switched to https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv plugin with the following changes to my `~/.zshrc`

```
#disable output during zsh intiatization or unless `typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet`
export AUTOSWITCH_SILENT=true 

#add support for pipenv autocompletion since MichaelAquilina/zsh-autoswitch-virtualenv don't add it
eval "$(_PIPENV_COMPLETE=zsh_source pipenv)"
```

Everything is working as expected as of now.

**Comment by Morningstar202604** [comment]
I'd like to take this one. From reading `plugins/pipenv/pipenv.plugin.zsh`, the auto-shell hook sources `"$(pipenv --venv)/bin/activate"` unconditionally whenever a Pipfile is present — so on a fresh directory whose virtualenv hasn't been created yet, the plugin leaks pipenv's stderr into shell startup and tries to `source` an empty expansion.

Plan: capture `pipenv --venv` with stderr silenced, and only source the activate script when the command succeeded and the file actually exists. The Python traceback itself is an upstream pipenv crash, but oh-my-zsh shouldn't surface it during `.zshrc` evaluation regardless.

**Comment by Morningstar202604** [comment]
PR #14021 opened to fix this — keeps activation and project directory in sync.
