### ISSUE TITLE
gitfast Completion Plugin Segfaults Zsh

### ISSUE THREAD

**Issue by jdavis** [ohmyzsh/ohmyzsh#2385]
Hiya!

I'm on CentOS 6.5 and using zsh 4.3.10. I was in a submodule of my home directory editing oh-my-zsh (a fork of oh-my-zsh and setup as a submodule in my dotfiles repo here on GitHub). I had a new plugin sitting in the plugins/ directory and went to add it like so:

``` bash
$ git add plugins/ce<tab>
```

and was logged out of SSH. I went to my Console access and saw this:

```
zsh[7099]: segfault at...
```

with a bunch of addresses and caused in `libc-2.12.so`.

I narrowed it down to the gitfast completion plugin. If anyone (like @felipec) has a fix, that'd be great!

Feel free to let me know if you need more details to debug it.

**Comment by cdkamat** [comment]
Just hit this on my system.

```
$ zsh --version
zsh 4.3.11 (x86_64-redhat-linux-gnu)
```

The actual segfault:

```
[609091.416878] zsh[129183]: segfault at 7faa2f283960 ip 00007faa2e76a94f sp 00007fff7a9e29c8 error 4 in libc-2.12.so[7faa2e637000+18a000]
```

gdb backtrace: 

```
(gdb) bt
#0  0x00007faa2e76a94f in __strlen_sse42 () from /lib64/libc.so.6
#1  0x000000000047a17d in ztrdup ()
#2  0x00007faa27f13569 in permmatches () from /usr/lib64/zsh/4.3.11/zsh/complete.so
#3  0x00007faa27f1063b in ?? () from /usr/lib64/zsh/4.3.11/zsh/complete.so
#4  0x0000000000461eb7 in getstrvalue ()
#5  0x0000000000460c9d in ?? ()
#6  0x0000000000461815 in getindex ()
#7  0x0000000000462afe in fetchvalue ()
#8  0x000000000047d390 in ?? ()
#9  0x0000000000481105 in prefork ()
#10 0x00000000004240cf in ?? ()
#11 0x0000000000424541 in ?? ()
#12 0x000000000042c923 in execlist ()
#13 0x000000000044e132 in execif ()
#14 0x00000000004244cb in ?? ()
#15 0x000000000042c923 in execlist ()
#16 0x000000000042d0b6 in execode ()
#17 0x000000000042d505 in runshfunc ()
#18 0x00007faa27f10029 in ?? () from /usr/lib64/zsh/4.3.11/zsh/complete.so
#19 0x000000000042d274 in runshfunc ()
#20 0x0000000000426b90 in doshfunc ()
#21 0x00007faa27f16a96 in ?? () from /usr/lib64/zsh/4.3.11/zsh/complete.so
#22 0x00007faa27f17cfe in do_completion () from /usr/lib64/zsh/4.3.11/zsh/complete.so
#23 0x00007faa2815c48d in ?? () from /usr/lib64/zsh/4.3.11/zsh/zle.so
#24 0x00007faa28157500 in completecall () from /usr/lib64/zsh/4.3.11/zsh/zle.so
#25 0x00007faa28148896 in execzlefunc () from /usr/lib64/zsh/4.3.11/zsh/zle.so
#26 0x00007faa28148ba1 in zlecore () from /usr/lib64/zsh/4.3.11/zsh/zle.so
#27 0x00007faa281493f0 in zleread () from /usr/lib64/zsh/4.3.11/zsh/zle.so
#28 0x000000000043e90e in zleentry ()
#29 0x0000000000442f6e in ingetc ()
#30 0x000000000043bfc6 in ?? ()
#31 0x000000000044c6c6 in zshlex ()
#32 0x000000000046c1e4 in parse_event ()
#33 0x000000000043fa69 in loop ()
#34 0x0000000000441dfe in zsh_main ()
#35 0x00007faa2e655d1d in __libc_start_main () from /lib64/libc.so.6
#36 0x000000000040dd69 in _start ()
```

I see this happening in the following scenario:
```
$ git add ../util/ <TAB>
```
Where the changed file is in util. This does not happen if I use the git plugin. Please let me know if more information is needed.

**Comment by cdkamat** [comment]
Updated to zsh 5.0.5 and the issue has done away.
